components/general/fonts/_fonts.scss, components/general/typography/_typography.scss, components/general/typography/typography.hbs, components/general/variables/_variables.scss
+ Edit typography classes 
+ Add font color 
+ Add levels of fonts
https://dev.snowdog.pro/issues/29900
=> Feature/29900 - Component with typography

components/blocks/cards/_cards.scss, components/blocks/cards/cards.hbs
+ Fix component with cards
+ edit styles and compare it with rwd
+ delete empty `image` tag + delete class b/c it's not necessary now
https://dev.snowdog.pro/issues/29980
=> Feature/29980 Fixed Card component

components/02-elements/image/image--picture.hbs, components/02-elements/image/image.config.js, components/02-elements/image/image.hbs
+ Add support to additional attributes and classes in `img` tag
+ Add `picture` tag with additional attributes, classes and img list
https://dev.snowdog.pro/issues/30647
=> #30647 - Image element

components/02-elements/container/_container.scss, components/02-elements/container/container.config.js, components/02-elements/container/container.hbs, docs/styles/_alpaca-components.scss
+ Add container core files
+ Add configuration `container` element - it's flexible
+ Add styles with variables to container element
+ Link element in styles
https://dev.snowdog.pro/issues/30591
=> Feature/30591 - Container element

components/02-elements/dropdown-menu/_dropdown-menu.scss, components/02-elements/dropdown-menu/dropdown-menu.config.js, components/02-elements/dropdown-menu/dropdown-menu.hbs, docs/styles/_alpaca-components.scss
+ Add core files of `dropdown-menu` element
+ Link in styles new element
https://dev.snowdog.pro/issues/30675/
=> Feature/30675 - Dropdown-menu element

components/02-elements/side-menu-trigger/_side-menu-trigger.scss, components/02-elements/side-menu-trigger/side-menu-trigger.config.js, components/02-elements/side-menu-trigger/side-menu-trigger.hbs, components/02-elements/side-menu-trigger/side-menu-trigger.js, docs/styles/_alpaca-components.scss
+ Add core files of `side-menu-trigger` element
+ Add link in styles to element
+ Add variant with only svg icon used
https://dev.snowdog.pro/issues/30685
=> Feature/30685 - Side-menu-trigger element

components/02-elements/side-menu/_side-menu.scss, components/02-elements/side-menu/side-menu.config.js, components/02-elements/side-menu/side-menu.hbs, docs/styles/_alpaca-components.scss
+ Add `side-menu` core files
+ Link in styles
https://dev.snowdog.pro/issues/30684
=> Feature/30684 - Add side-menu

components/03-modules/header/_header.scss, components/03-modules/header/header.hbs, docs/styles/_alpaca-components.scss
+ Add necessary elements in header
+ Remove placeholders and test if it's wokring
+ Link header in styles 
+ Add basic styles to header
=> Feature/30687 - Header module

components/01-globals/grid/_grid.scss
+ Fix typo bug in grid 
https://dev.snowdog.pro/issues/30707
=> #30707 - Typo fix in grid

components/02-elements/breadcrumbs/_breadcrumbs.scss
+ rebuild breadcrumb styles now working on flexbox
https://dev.snowdog.pro/issues/31162
=> #31162 - Breadcrumbs styles

components/01-globals/typography/link/_link.scss
+ Add transition variable
+ Add font-family variable
+ Add font-weight variable
https://dev.snowdog.pro/issues/33992
=> Feature/33992 - Update link styles

components/02-elements/dropdown-menu/dropdown-menu.hbs, components/02-elements/image/_image.scss, components/02-elements/image/image--picture.hbs, components/02-elements/image/image.config.js, components/02-elements/image/image.hbs
+ Adjust img element to rendering html and shortcut names
=> #34965 - Img element

components/01-globals/_fonts/_fonts.scss, components/01-globals/typography/heading/_heading.scss, components/01-globals/variables/_variables.scss
+ Change font to multiple font-weight and one font
+ Update typography heading and variables
#115
https://dev.snowdog.pro/issues/35204
=> Feature/35204 - Font update

CHANGELOG.md, components/02-elements/password-strength/_password-strength.scss
+ Edit variables and name of modifiers
+ Update CHANGELOG.md
#117
https://dev.snowdog.pro/issues/35415
=> #35415 - Password strength

CHANGELOG.md, components/02-elements/table/_table.scss
+ Update table styles to responsive
#145
https://dev.snowdog.pro/issues/35526
=> Feature/35526 - Table

components/_preview.hbs
+ Add all required meta tags
#147 
https://dev.snowdog.pro/issues/35663
=> #35663 - Meta viewport tag

CHANGELOG.md, components/01-globals/icons/files/minus.svg, components/01-globals/icons/icons.config.js, components/03-modules/quantity-update/_quantity-update.scss, components/03-modules/quantity-update/quantity-update.config.js, components/03-modules/quantity-update/quantity-update.hbs, docs/styles/_alpaca-components.scss
+ Add minus icon and list it in icon config
+ Add qty updater files
+ Link in styles
#107 
https://dev.snowdog.pro/issues/35653
=> Feature/35653 - Qty updater

components/02-elements/form/select/_select.scss
=> Update class in select element

components/02-elements/list/_list.scss, components/02-elements/list/list.config.js, docs/styles/docs-only-styles/_list.scss, docs/styles/styles.scss
Fixes #185 
https://dev.snowdog.pro/issues/36090
=> Move list styles that are not necessary in component to docs styles #185 / feature/36090

components/02-elements/dropdown-list/dropdown-list--with-nested.hbs, components/02-elements/dropdown-list/dropdown-list.config.js, components/02-elements/dropdown-list/dropdown-list.hbs
Fixes #210 
https://dev.snowdog.pro/issues/36272
+ Edit preview files
+ Edit config file
=> #36272 - Dropdown list - improvement

CHANGELOG.md, components/01-globals/_focus/_focus.scss, docs/styles/_alpaca-components.scss
https://dev.snowdog.pro/issues/36363
add focus style - using box shadow instead with `outline: none;`
=> Global focus style Feature/36363

components/02-elements/tab/tab.config.js, components/02-elements/tab/tab.hbs
=> #36596 - Tab improve

CHANGELOG.md, components/03-modules/modal/_modal.scss, components/03-modules/modal/modal.js
=> #36647 - modal - added condition for close button and updated changelog

CHANGELOG.md, components/01-globals/typography/label/_label.scss
=> Accessibility utilities - Feature/36637

components/02-elements/cookie-message/_cookie-message.scss
Refs: #233 
internal: dev-36656
=> Update cookie msg colors and icon size to match updates in design Refs #233, dev-36656

components/02-elements/logo/logo.config.js, components/02-elements/logo/logo.hbs, components/03-modules/header/header.config.js
Refs #247  dev-36634 
- add image source as path in config plus some extra attributes like href, custom attr for image, image class
- update header logo config to match new changes
=> update logo template and config to make it more customizable Refs #247  dev-36634 

components/03-modules/newsletter/_newsletter.scss
Refs: #254 
Internal: dev-36635
=> fix IE issue with placeholder vertical alignment for newsletter input

components/02-elements/form/select/_select.scss
Add height and border-radius to native styles
DEV-36716
=> #36716 - Update native select to magento theme

components/02-elements/form/file-upload/file-upload.js
Refs: #271 
internal: dev-36976
=> Refactor code to improve security , refs #271, dev-36976

CHANGELOG.md, components/02-elements/form/file-upload/file-upload.config.js, components/02-elements/form/file-upload/file-upload.hbs, components/02-elements/form/file-upload/file-upload.js
#193 
internal: dev-Support #36913
=> #36913 file upload accessibility

components/03-modules/slider/slider.js
DEV-37661
Improve some things, changes a lot, make this code better, faster, stronger.
=> #37661 - Rewrite script for slider, avoid functions inside loop

components/02-elements/dropdown-list/dropdown-list.config.js, components/02-elements/dropdown-list/dropdown-list.hbs, components/02-elements/tab/_tab.scss, components/02-elements/tab/tab.config.js, components/02-elements/tab/tab.hbs, components/02-elements/tab/tab.js, components/03-modules/dashboard/table/table.hbs, components/03-modules/footer/footer.config.js, components/03-modules/minicart-product/minicart-product.config.js, components/04-views/product-view/product-view.config.js, components/04-views/product-view/product-view.hbs
Refs: #294
internal: dev-37439
=> added script support for more components

components/02-elements/tab/tab.js
Refs: #299
internal: dev-37439
=> fixed bug with closing tab

components/02-elements/tab/_tab.scss, components/02-elements/tab/tab.config.js, components/02-elements/tab/tab.hbs, components/02-elements/tab/tab.js, components/04-views/product-view/product-view.config.js
Refs: #305 #304
internal: dev-37785
=> Tab bugs and clean-up

components/02-elements/tab/tab.js
`/components/02-elements/tab/tab.js`
```
19:1  error  Trailing spaces not allowed  no-trailing-spaces
27:1  error  Trailing spaces not allowed  no-trailing-spaces
=> trailing spaces error

components/03-modules/quantity-update/quantity-update.config.js, components/03-modules/quantity-update/quantity-update.hbs, components/03-modules/quantity-update/quantity-update.js
=> Add quantity update js

CHANGELOG.md
=>  Missing changelog update from quantity-update 38277 branch

components/02-elements/form/select/_select.scss
+ add styles to dropdown in select
DEV-37783
=> #37783 - add styles to select dropdown

components/03-modules/dashboard/nav/_nav.scss, components/04-views/dashboard/default/_dashboard.scss
=> #37752 - Update dashboard styles

components/02-elements/logo/_logo.scss
DEV-39220 
Avoid abnormally height of header in ie11
=> #39220 - Avoid error with abnormally height in header in ie11

components/04-views/dashboard/wishlist/wishlist.config.js
=> Wishlist config button

components/01-globals/typography/heading/heading.hbs, components/02-elements/form/input/input--textarea.hbs, components/02-elements/form/input/input.config.js, components/02-elements/form/input/input.hbs, components/02-elements/form/select/select.config.js, components/02-elements/form/select/select.hbs, components/03-modules/minicart-product/minicart-product.config.js, components/03-modules/toolbar/toolbar.config.js, components/04-views/cart/cart.config.js, components/04-views/login/login.config.js, components/04-views/registration/registration.config.js
Internal: 39695
#312 
* Rename existing attributes
* Add attributes to heading and select elements
=> Feature/39695 - Attributes

components/02-elements/popup-trigger/popup-trigger.config.js, components/02-elements/popup-trigger/popup-trigger.hbs
=> #288 - added merge true

README.md
=> #40272 - Add browser support badges

components/02-elements/image/_image.scss, components/02-elements/image/image.hbs, components/03-modules/catalog-grid-item/catalog-grid-item.config.js, components/03-modules/catalog-grid-item/catalog-grid-item.hbs, components/03-modules/catalog-list-item/catalog-list-item.config.js, components/03-modules/catalog-list-item/catalog-list-item.hbs
=> Placeholder for lazyload image

CHANGELOG.md, components/02-elements/list/_list.scss, components/03-modules/filters/_filters.scss
=> #45656 - Add style for category block in catalog view

components/04-views/catalog/list/_list.scss
=> #45727 - Fix sidebar block floating when filters are open

components/02-elements/breadcrumbs/_breadcrumbs.scss
=> #45950 - Fix first item size in breadcrumbs

CHANGELOG.md, components/04-views/_components.scss, components/04-views/confirmation-link/_confirmation-link.scss, components/04-views/confirmation-link/confirmation-link.config.js, components/04-views/confirmation-link/confirmation-link.hbs
=> #48503 - Add confirmation-link view

CHANGELOG.md, components/02-elements/rating/_rating.scss
=> fix rating focus position

CHANGELOG.md, components/03-modules/mega-menu/_mega-menu.scss, components/03-modules/mega-menu/mega-menu.hbs, components/03-modules/mega-menu/mega-menu.js
https://dev.snowdog.pro/issues/51573
=> #51573 - Changed hover menu class to active on mega menu

CHANGELOG.md, components/01-globals/libs/libs.hbs, components/02-elements/dropdown-list/dropdown-list.config.js, components/02-elements/dropdown-list/dropdown-list.hbs, components/02-elements/dropdown-list/dropdown-list.js, components/03-modules/footer/footer.config.js, components/03-modules/minicart-content/minicart-content.config.js, components/03-modules/side-menu/side-menu.config.js
=> #54599: change dropdown list selector and remove duplicated class declaration 

CHANGELOG.md, components/02-elements/_components.scss, components/02-elements/skip-nav/_skip-nav.scss, components/02-elements/skip-nav/skip-nav--list.hbs, components/02-elements/skip-nav/skip-nav.config.js, components/02-elements/skip-nav/skip-nav.hbs, components/02-elements/skip-nav/skip-nav.js
#154
[dev-51564](https://dev.snowdog.pro/issues/51564)
=> #51564 - Add skip-nav element
